CREATE TABLE USER (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME  VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED_DATE TIMESTAMP,
    LAST_LOGIN_DATE TIMESTAMP
)