CREATE TABLE TRANSACTION (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION LONGTEXT,
    AMOUNT DECIMAL(19, 4) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    CATEGORY VARCHAR(255),
    TYPE VARCHAR(255) NOT NULL
)